### ISSUE TITLE
Allow specifying audio/video quality

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode.Converter#1]
- How to specify the desired video quality?
- Should it simply download muxed streams if the desired media quality is low?

**Comment by newbiedeveloper9** [comment]
Hey, my project is using both of your libraries (Explode and Converter) and waiting for this feature. Can I know priority of this enhancement? If you're out of time and can't do it in nearest time then i'll do it on my own, just want to know. 
Btw, those libraries are core of my main project so i'm really thankful

**Comment by Tyrrrz** [comment]
Hi and thank you for using my libraries. It's nice to hear.

This enhancement is definitely something I'm interested in, but I don't have time in the nearest few weeks to work on it, so you're welcome to help.
