### ISSUE TITLE
Best way of implementing without dependency of YoutubeExplode ?

### ISSUE THREAD

**Issue by ConsultantsCombined** [Tyrrrz/YoutubeExplode.Converter#11]
I am having troubles implementing this library, I want to be able to include it and not have to worry about the reference of your YoutubeExplode.DLL being in that project also as I modified it myself based on comments to do with JSON structure change with YoutubeExplode here https://github.com/Tyrrrz/YoutubeExplode. 

Am using the code from your download audio and video muxed and getting an error likely due to that json issue in the youtubeexplode.dll reference. Will update with error when i have more information

**Comment by Tyrrrz** [comment]
As long as binding redirects are there, you can substitute other versions of the dependency assembly.
