### ISSUE TITLE
System cannot find the File

### ISSUE THREAD

**Issue by Marly212** [Tyrrrz/YoutubeExplode.Converter#12]
Hello,

I tried this Code:

![grafik](https://user-images.githubusercontent.com/42452096/61515826-ce0b9480-aa03-11e9-979b-932003e75166.png)

when I run my Programm to Download the Video it always says that the System cannot find the File.

Since I am a beginner in C# I am a little bit clueless.

Hope someone can help me.

My goal is to get the Video with the Audio and the Video on Max Quality

**Comment by Tyrrrz** [comment]
You need to have FFmpeg.exe in the same folder as your app.
You can use [this](https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/master/YoutubeExplode.Converter.Tests/DownloadFfmpeg.ps1) script.

**Comment by Marly212** [comment]
I already check that one, and I have ffmpeg.exe in the same folder

![grafik](https://user-images.githubusercontent.com/42452096/61529773-85af9f00-aa22-11e9-849a-07ace2a8fcfe.png)

I have ffmpeg.exe in the Debug folder from the Visual Studio Projekt and in the Folder before

**Comment by Tyrrrz** [comment]
>My goal is to get the Video with the Audio and the Video on Max Quality

Btw, this should be the default behavior, so you can use the simpler api, i.e. `DownloadVideoAsync()`.

**Comment by Tyrrrz** [comment]
As for the error, I need the stacktrace, otherwise I can't tell you what's happening.

**Comment by Marly212** [comment]
> 
> 
> > My goal is to get the Video with the Audio and the Video on Max Quality
> 
> Btw, this should be the default behavior, so you can use the simpler API, i.e. `DownloadVideoAsync()`.

And which stream do I give "DownloadVideoAsync"? 
By "mediaStreamInfoSet" i get the same Error

**Comment by Tyrrrz** [comment]
You don't, you just specify video id

**Comment by Marly212** [comment]
Ok it worked.

Thanks

**Comment by Tyrrrz** [comment]
Glad it worked :0
