### ISSUE TITLE
IProgress<T> may report duplicate progress values

### ISSUE THREAD

**Issue by BlauFx** [Tyrrrz/YoutubeExplode.Converter#13]
It happens **sometimes** when I try do download a playlist (works especially when one video is large)

Here's an example:
```
private static IProgress<double> prog = new Progress<double>(HandleProgress);

await converter.DownloadAndProcessMediaStreamsAsync(mediaStreamInfos, "path", "mp4", prog);

private static void HandleProgress(double progress) 
{
	Console.WriteLine(progress.ToString()
}
```
The result:
https://gist.github.com/BlauFx/1fbefc1bfc5d5faeac2ceb7a31a2f941#file-result-L1622

As you can see at line 1622 or at 3332
the number 1 is twice there

**Comment by Tyrrrz** [comment]
Is it possible for you to add a check that ignores duplicate values?

**Comment by BlauFx** [comment]
Yes it is possible. I'm gonna do it then by myself.
