### ISSUE TITLE
Win32Exception: Access is denied

### ISSUE THREAD

**Issue by hpenney2** [Tyrrrz/YoutubeExplode.Converter#17]
I have the following code:
```cs
var info = await client.GetVideoMediaStreamInfosAsync(searchArray[0].Id);
var converter = new YoutubeConverter(client, Directory.GetCurrentDirectory());
await converter.DownloadVideoAsync(info, "song.opus", "opus");
```
When the 3rd line runs, I get a Win32Exception: `Access is denied`. Did I do something wrong or...?

**Comment by hpenney2** [comment]
Here's the stack trace if that's helpful:
![](https://cdn.discordapp.com/attachments/381889909113225237/647886291597525003/unknown.png)

**Comment by Tyrrrz** [comment]
Looks like something is denying access to `ffmpeg.exe` for some reason.

**Comment by hpenney2** [comment]
I changed `new YoutubeConverter(client, Directory.GetCurrentDirectory());` to `new YoutubeConverter(client)` and that seems to have fixed the problem. The first time it ran the converter seemed to have took longer, but after that it seems to run much quicker.

**Comment by Tyrrrz** [comment]
Great :)

**Comment by hpenney2** [comment]
Do you know why it takes so long to download the first time after the application runs? (20-30 seconds, then goes down to about 5 seconds)

**Comment by Tyrrrz** [comment]
No idea. Is it consistent?

**Comment by hpenney2** [comment]
In a way, yes. Every time I start the program, the first one or two times takes about 20 seconds to 1 minute (depending on the video length). After that, short videos usually take around 5 seconds, and longer ones take up to ~15-20 seconds.

**Comment by Tyrrrz** [comment]
I'm not sure what could cause this
