### ISSUE TITLE
DownloadAndProcessMediaStreamsAsync throws 403

### ISSUE THREAD

**Issue by Headhuntez** [Tyrrrz/YoutubeExplode.Converter#19]
Метод в половине случаев вызывает внутреннее исключение: HttpRequestException: Код состояния ответа не указывает на успешное выполнение: 403 (Forbidden).

_-i-Video #03 [Vp9 3840x1620 25fps]. Audio [Opus 139398 webm 251 3210135]...
-i-Downloading and Converting... [03 Hard Driver - Blow Da Club Down (Official Video)]
-x-Error DownloadAndProcessMediaStreams [https://www.youtube.com/watch?v=Rq-E1jBP6Ss]_

Что может быть причиной? это у меня одного так? спустя пол часа из 5 одно видео все таки получилось остальные такие же.

**Comment by Tyrrrz** [comment]
Caused by https://github.com/Tyrrrz/YoutubeExplode/issues/344, should be fixed soon.
