### ISSUE TITLE
Running on Android: path1 cannot be nulled

### ISSUE THREAD

**Issue by jamg26** [Tyrrrz/YoutubeExplode.Converter#20]
case1:
var client = new YoutubeClient();
var converter = new YoutubeConverter(client);

case2:
var converter = new YoutubeConverter();

the same error 
path1 cannot be nulled;

**Comment by Tyrrrz** [comment]
Looks like `AppDomain.CurrentDomain.BaseDirectory` is null for you. What application are you building?

**Comment by jamg26** [comment]
xamarin forms building it for android

**Comment by Tyrrrz** [comment]
This package only supports desktop platforms. I'm not sure what you would use with Xamarin for FFmpeg.

**Comment by jamg26** [comment]
using it for youtube to mp3 download for mobile, for pocket use. Many of us here looking for this kind of app.

**Comment by Tyrrrz** [comment]
I can't advise here because I haven't worked with mobile platforms myself.

**Comment by Tyrrrz** [comment]
At the very least the library can provide a more descriptive error that the OS platform is not supported.
