### ISSUE TITLE
Separate the download and the conversion to separate threads

### ISSUE THREAD

**Issue by Jeager2** [Tyrrrz/YoutubeExplode.Converter#21]
When doing this:

// Download and process them into one file
await converter.DownloadAndProcessMediaStreamsAsync(streamInfos, "video.mp4", "mp4");

The downloads take place and then it must convert before continuing to download. 
I suggest that these are separate tasks and should be split into separate threads. That way downloads can continue to stream while conversion takes place.

Example:
Downloading 5 files
Time Spent downloading =D 
Time Spent Converting= C

Currently
DCDCDCDCDC

Suggestion
----------
DDDDD
__CCCCC 

Time Difference
DCDCDC**DCDC** <---- Current
DDDDDC <----- New Suggestion 
(Conversions are happening simultaneous to downloads, except for the last download, of course) 

Thanks for some wonderful code btw.

**Comment by Tyrrrz** [comment]
This could be probably done with named pipes and avoiding intermediary files.

**Comment by Jeager2** [comment]
> This could be probably done with named pipes and avoiding intermediary files.
Yes, but doing that does not solve the issue for me.

What I want is :
1) a function to download the streams.
2) a function to convert the downloaded streams.
that way I can put them in different sections of code and they can run independently.
Waiting for conversion to complete before starting next download wastes a lot of time for me.

Avoiding the creation of temp files is not useful in my situation.

I suggest:
DownloadAndProcessMediaStreamsAsync(
DownloadMediaStreamsAsync(
ProcessMediaStreamsAsync(

and if you want to create it:
DownloadAndProcessMediaStreamsNamedPipesAsync(

thank you

**Comment by SlowLogicBoy** [comment]
Because of temp files it's _maybe_ a good Idea to separate them to separate logic, however temp files are what is sketchy, with no temp files it doesn't makes sense to separate threads, since download is slower then conversion. If separation happens then it will be more difficult to refactor code to avoid temp files.

**Comment by Jeager2** [comment]
For my machine conversion takes almost the same time as download so it effectively doubles the time it takes to get files. I'm running a 16 core Ryzen 1800x and 16GB ram, but my max download is about 3MB/s. Some downloads take 30 minutes (4k video) and then take 30 minutes to mux.

How about you support both ways Download, Convert and DownloadAndConvert ?

I know I could use your youtubedownloader to download both streams and then take your YoutubeExplode.Converter and refactor the code to just handle conversion myself. I was just hoping to not fork and keep using your project directly.

Thanks for considering

**Comment by Jeager2** [comment]
Consider a playlist like this:

**Comment by Tyrrrz** [comment]
Note: Named pipes turned out to be a failed experiment. It seems they are occasionally slower than files and also the .NET implementation doesn't work very well on Unix systems.

**Comment by rpm61** [comment]
Has there been a change here? I jumped in to maintaining code for someone else, and updated the nugets due to recent errors in GetManifestAsync. I now find trhat I am receiving Type 'YoutubeConverter' is not defined. , this was being used for DownloadAndProcessMediaStreamsAsync.

**Comment by Tyrrrz** [comment]
I think you're commenting on an unrelated issue, but yes, the last version (2.x) was breaking and has a new API. Migrating should be pretty simple though, the readme has new examples.

**Comment by rpm61** [comment]
Sorry for that

**Comment by Tyrrrz** [comment]
Closing this issue pending a merger with the main repository. Will reopen there once it's complete.
