### ISSUE TITLE
Videos sometimes download and convert to .webm instead of MP4

### ISSUE THREAD

**Issue by Jeager2** [Tyrrrz/YoutubeExplode.Converter#22]
Example URL:
https://www.youtube.com/watch?v=pgzWxOtk1zg

This will download when downloading 1) Highest Video AND 2) Highest Audio Quality and merge the strreams using ffmpeg to .WEBM file. 

I believe this is a bug.  ? 
Is there a way to force this to be muxed as a MP4? Am I missing something?

Code Example:
var streamManifest = await client.Videos.Streams.GetManifestAsync(id);

// Get highest quality video-only stream
var streamInfoVideo = streamManifest.GetVideoOnly().WithHighestVideoQuality();

// Get highest quality Audio-only stream
var streamInfoAudio = streamManifest.GetAudioOnly().WithHighestBitrate();

var converter = new YoutubeConverter();
// Combine them into a collection
var streamInfos = new IStreamInfo[] { streamInfoAudio, streamInfoVideo };

// Get file extension based on stream's container
ext = streamInfoVideo.Container.Name; <-- Can I Change this to force mp4?

// Download and process them into one file
await converter.DownloadAndProcessMediaStreamsAsync(streamInfos, Path.Combine(path, $"{titleTemp}.{ext}"), "mp4");

// IS THIS A SAFE ALTERNATIVE?
await converter.DownloadAndProcessMediaStreamsAsync(streamInfos, Path.Combine(path, $"{titleTemp}.{"mp4"}"), "mp4");

Thanks

**Comment by Tyrrrz** [comment]
Hmm, by the looks of the code, FFmpeg ignores the provided format and just infers if from file name. Yes, you should specify `$"{titleTemp}.mp4"` instead. You would only use `streamInfoVideo.Container.Name` if you wanted to use the same container as the video stream.

**Comment by Jeager2** [comment]
Thank you for the quick response.
