### ISSUE TITLE
Error from ffmpeg when download webm

### ISSUE THREAD

**Issue by Isayso** [Tyrrrz/YoutubeExplode.Converter#24]
Thanks for your great library! Wish I had seen it earlier.

When I download webm file, CPU goes to high load, a webm file is written only for a length of some seconds. In the task manager I see a high load in ffmpeg, when I cancel the ffmpeg task the error dialog from my try/catch code with ffmpeg error comes up.
With mp4 everything works fine! I use the last ffmpeg 64bit version 

await converter.DownloadAndProcessMediaStreamsAsync(streamInfos, videoTitle, "webm");
  thanks!

![Screenshot (100)](https://user-images.githubusercontent.com/35309607/82731092-bc220e80-9d04-11ea-81ec-7fab5236c010.jpg)

**Comment by Isayso** [comment]
Audio is mp4a.40.2
Video webm vp9 1080p

I stopp the process after several minutes of ffmpeg processing on a i7 6 core Dell. Doesn't look like the process will succeed (?). I tried with several YT Videos. 

The same with mp4 option was some seconds.

**Comment by Tyrrrz** [comment]
Could you try again, killing the process when it gets stuck (`...stream-1.tmp` and `...stream-2.tmp` files should remain) then run `cmd` and execute the command shown in the error message manually to see what FFmpeg says?

**Comment by Isayso** [comment]
I'm too stupid to use ffmpeg at cmd  

ffmpeg -i xxx-1.tmp xxx-2.tmp {test.webm}      ?

**Comment by Tyrrrz** [comment]
Yes, the exact command is written in the error message you took a screenshot of (after "Command:" and before "You can suppress..."):

![image](https://user-images.githubusercontent.com/1935960/82736693-5188c700-9d34-11ea-875c-b8e9d9e94878.png)

**Comment by Isayso** [comment]
Ok, its doing something with 13fps !!!!!

    encoder         : google/video-file
  Duration: 00:03:26.64, start: 0.000000, bitrate: 1741 kb/s
    Stream #1:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
Codec AVOption preset (Configuration preset) specified for output file #0 (test.webm) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #1:0 -> #0:0 (vp9 (native) -> vp9 (libvpx-vp9))
  Stream #0:1 -> #0:1 (aac (native) -> opus (libopus))
[libvpx-vp9 @ 000001e04682e200] v1.8.1-133-g802569640
[libopus @ 000001e046cb6b00] No bit rate set. Defaulting to 96000 bps.
Output #0, webm, to 'test.webm':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.32.104
    Stream #0:0(eng): Video: vp9 (libvpx-vp9), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 200 kb/s, 29.97 fps, 1k tbn, 29.97 tbc (default)
    Metadata:
      encoder         : Lavc58.56.101 libvpx-vp9
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
    Stream #0:1(und): Audio: opus (libopus), 48000 Hz, stereo, flt, 96 kb/s (default)
    Metadata:
      creation_time   : 2019-06-09T10:47:26.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 06/09/2019.
      encoder         : Lavc58.56.101 libopus
frame=  859 fps= 12 q=0.0 size=     995kB time=00:00:27.85 bitrate= 292.7kbits/s speed=0.395x

**Comment by Tyrrrz** [comment]
Does it complete?

**Comment by Isayso** [comment]
fps was declining down to 7fps, I stopped ist with crtl-c, webm file can be played. So a ffmepg performance problem?

**Comment by Tyrrrz** [comment]
Assuming it takes the same amount of time, then yes, it's FFmpeg-related. You can try to change the preset from "medium" to "ultrafast" and see how it fares. This will produce a larger output file but should complete faster.

**Comment by Isayso** [comment]
only a small increase to 14fps. I used youtube-dl/ffmpeg before to muxx and had not such issue, but the ffmepg version was older.

**Comment by Tyrrrz** [comment]
Can you give me the video URL and minimal code repro?

**Comment by Isayso** [comment]
Sure
https://www.youtube.com/watch?v=GWLke36Z73A
  
https://github.com/Isayso/PlaylistEditor2/blob/dev/KodiPlaylistEditor/ClassYTExplode.cs  

Line 212

**Comment by Tyrrrz** [comment]
Hm. I just tried it with this code:

```csharp
var converter = new YoutubeConverter();
await converter.DownloadVideoAsync("https://www.youtube.com/watch?v=GWLke36Z73A", "output.webm", "webm");
```

And it completed in about 3 seconds.

**Comment by Isayso** [comment]
thats odd. Its also only some seconds when I use mp4 but not webm, even with the older ffmpeg.

No idea, but thanks for your support!!!  Will do it on a different PC to cross check.

**Comment by Tyrrrz** [comment]
Does it work any faster if you use the exact same code as me?

**Comment by Isayso** [comment]
Yes, as quick as mp4 with DownloadAndProcess.....

**Comment by Tyrrrz** [comment]
Hm, then something is wrong about the specific streams you selected.

**Comment by Isayso** [comment]
I found the error!  One must set the same Container for audio and video. `GetAudio().WithHighestBitrate();` can get the mp4 Container and **ffmpeg has performance issue to combine mp4 audio with webm video**. 

**Thanks a lot for your help!**  

`//get manifest`
`var streamManifest = await _youtube.Videos.Streams.GetManifestAsync(videoId);`

`//select best audio  **ERROR gets mp4 container**`
`var audioStreamInfo = streamManifest.GetAudio().WithHighestBitrate();`

`//set webm container for audio`
`var audioStreamInfo = streamManifest.GetAudio()`
                                      `     .Where(s => s.Container == Container.WebM)`
`                                           .WithHighestBitrate();`

`//select video smaller or equal of designated quality, webm container`
`var videoStreamInfo = streamManifest.GetVideoOnly()`
                                     `       .Where(s => s.VideoQuality <= VideoQuality.High1080)`
                                   `       .Where(t => t.Container == Container.WebM)`
                                    `     .First();`

`//combine audio,video`
`var streamInfos = new IStreamInfo[] { audioStreamInfo, videoStreamInfo };`

`//get Video Info`
`VideoInfo = await _youtube.Videos.GetAsync(videoId);  `

`//target path + VideoInfo.Title + fileextension`
`videoTitle = targetpath + "\\" + RemoveSpecialCharacters(VideoInfo.Title) + "." + filetype[fileext];`

`//download`
               `     await converter.DownloadAndProcessMediaStreamsAsync(streamInfos, videoTitle, "webm");`
`

**Comment by Tyrrrz** [comment]
You're welcome :)
