### ISSUE TITLE
Mix various audios?

### ISSUE THREAD

**Issue by rigorvzla** [Tyrrrz/YoutubeExplode.Converter#27]
Hello , is posible mix various mp3 (10 files mp3) ??
if is posble how can do?

**Comment by Tyrrrz** [comment]
What do you mean by mixing 10 mps files?

**Comment by rigorvzla** [comment]
i wanna mix 3 videos (only audio) in 1 file mp3, is posible

**Comment by Tyrrrz** [comment]
I don't think it will work out, probably best to use FFmpeg manually.

**Comment by rigorvzla** [comment]
mm ok thanks ;) good day

**Comment by rigorvzla** [comment]
mm ok thanks ;) good day
