### ISSUE TITLE
Suggested code on your readme

### ISSUE THREAD

**Issue by Jeager2** [Tyrrrz/YoutubeExplode.Converter#28]
Here is some suggested code to add after "Download specific streams" section to show the ease of use and capabilities exposed.

Download specific streams - (Highest Quality available)
var youtube = new YoutubeClient();

 YoutubeExplode.Videos.Video video = await client.Videos.GetAsync(id);
  // Retrieving some values from the video
  string title = video.Title;
  string titleTemp = video.Title;
  string OrigTitle = video.Title;
  string author = video.Author;
  TimeSpan duration = video.Duration;
  DateTime videoUploadDate = video.UploadDate.DateTime;

  //Safe Filenames
  foreach (char lDisallowed in Path.GetInvalidFileNameChars())
  {
       title = title.Replace(lDisallowed.ToString(), "");
       OrigTitle = OrigTitle.Replace(lDisallowed.ToString(), "");
  }
  string SafeTitle = title;

StreamManifest streamManifest = await client.Videos.Streams.GetManifestAsync(id);

// Get highest quality video-only stream
IStreamInfo streamInfoVideo = streamManifest.GetVideoOnly().WithHighestVideoQuality();

// Get highest quality Audio-only stream
IStreamInfo streamInfoAudio = streamManifest.GetAudioOnly().WithHighestBitrate();

// Combine them into a collection
var streamInfos = new IStreamInfo[] { streamInfoAudio, streamInfoVideo };

//Set File extension explicitly
ext = "mp4";

// Download and process them into one file
await client.Videos.DownloadAsync(streamInfos, new ConversionRequestBuilder(Path.Combine(path, $"{SafeTitle}.{ext}")).Build());

**Comment by Tyrrrz** [comment]
I'm not sure what's the main difference?

**Comment by Jeager2** [comment]
This code is in addition to what you already have, it's not a replacement. It would be as a new example. 
I had to look for these features and think it would save others work...

It shows off .WithHighestVideoQuality(); and .WithHighestBitrate(); 

The "//Safe Filenames" section is just a helper that helps people who try to save a file that has an invalid character and it fails.

This shows how to force conversion to mp4
//Set File extension explicitly
ext = "mp4";

**Comment by Tyrrrz** [comment]
Ah. Well that's a feature of YoutubeExplode and it's documented here already: https://github.com/Tyrrrz/YoutubeExplode#downloading-a-video-stream

> This shows how to force conversion to mp4
//Set File extension explicitly
ext = "mp4";

The `ext` variable doesn't exist in that context, but a better way to enforce format is:

```csharp
new ConversionRequestBuilder(outputPath).SetFormat("mp4").Build();
```

**Comment by Jeager2** [comment]
I’ve tried that before but occasionally it would download webm files even when specified.

**Comment by Tyrrrz** [comment]
That's a bug then.

**Comment by Tyrrrz** [comment]
Created issue for that #29.
