### ISSUE TITLE
Specified format is sometimes ignored in favor of file extension

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode.Converter#29]
Looks like sometimes FFmpeg prioritizes the format from the file extension instead of the one provided.

**Comment by Jeager2** [comment]
Notably if you specify format like “.mp4” instead it will use the format you specified. (MP4)

**Comment by Tyrrrz** [comment]
Do you mean `SetFormat(".mp4")`? Or in file name?

**Comment by Jeager2** [comment]
Like this: (I’m not at the pc right now so this might be using old method names. )

converter.DownloadAndProcessMediaStreamsAsync(streamInfos, "video.mp4", "mp4");

I would love to be able to specify options to ffmpeg if that was/is exposed.

**Comment by Tyrrrz** [comment]
Apparently to fix this, the format option must come before the input option(s):

https://superuser.com/a/976990

**Comment by Tyrrrz** [comment]
Closing this issue pending a merger with the main repository. Will reopen there once it's complete.
