### ISSUE TITLE
Rethrow standard error on failure

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode.Converter#33]
Related to #32 

Need to add [one more pipe](https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/db350e0a99ad8eca55c0df99fe30c149facabe14/YoutubeExplode.Converter/FFmpeg.cs#L78-L81) (with `PipeTarget.Merge`) to collect standard error and throw it with an exception in case FFmpeg returns non-zero exit code.

**Comment by Druffl3** [comment]
I would like to work on this issue. Also, it'll be helpful if you can add a contributions.md file which can help in understanding prerequisites for contributing and a general project overview.

**Comment by Tyrrrz** [comment]
Go ahead @Druffl3.

As for prerequisites, it should be pretty straightforward. The only hard dependency is latest .NET SDK. The tests require FFmpeg, but they download it automatically.

If you have any questions, you can ask here and I'll help.
