### ISSUE TITLE
Exception: Method not found: 'Int64 YoutubeExplode.Videos.Streams.FileSize.get_TotalBytes()

### ISSUE THREAD

**Issue by Jeager2** [Tyrrrz/YoutubeExplode.Converter#35]
I'm Using Youtube explode 6.0.0.0
and YoutubeExplode.Converter 2.0.2.0 which I believe are the latest versions.

When I look at the streamInfoVideo and streamInfoAudio objects they do have a size property that is set.

Code Snip below:
using YoutubeExplode;
//using YoutubeExplode.Models.MediaStreams;
using YoutubeExplode.Videos.Streams;
using YoutubeExplode.Converter;
using YoutubeExplode.Common;

StreamManifest streamManifest = await client.Videos.Streams.GetManifestAsync("https://youtu.be/" + id);
// Get highest quality video-only stream
IStreamInfo streamInfoVideo = streamManifest.GetVideoOnlyStreams().GetWithHighestVideoQuality();
// Get highest quality Audio-only stream
IStreamInfo streamInfoAudio = streamManifest.GetAudioOnlyStreams().GetWithHighestBitrate();

//Set File extension explicitly
//ext = streamInfoVideo.Container.Name;
ext = "mp4";
// Download and process them into one file

await client.Videos.DownloadAsync(streamInfos, new ConversionRequestBuilder(Path.Combine(path, $"{titleTemp}.{ext}")).Build());

I get an exception at this point:
Exception: Method not found: 'Int64 YoutubeExplode.Videos.Streams.FileSize.get_TotalBytes()

**Comment by Tyrrrz** [comment]
YoutubeExplode.Converter is not compatible with YoutubeExplode 6.0 yet. I will release a new version soon.

**Comment by Jeager2** [comment]
Confirmed working. Thank you so much!
