### ISSUE TITLE
Question maybe not an issue about Audio Streams to WAV format

### ISSUE THREAD

**Issue by inetmarketeers** [Tyrrrz/YoutubeExplode.Converter#36]
I am able to get the MP3 output, but does the converter include an option to save to WAV instead of MP3?

**Comment by Tyrrrz** [comment]
Yes. The converter just wraps FFmpeg so it's up to the latter if it supports it or not. You can set a custom format here:

https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/24428eda4cd7c391054579f2a66dcce6dbbbe5e9/YoutubeExplode.Converter/ConversionRequestBuilder.cs#L51
