### ISSUE TITLE
standard exception using xamarin forms.

### ISSUE THREAD

**Issue by scooby0344** [Tyrrrz/YoutubeExplode.Converter#4]
Hello,

I'm attempting to use your library for a xamarin forms project.  I'm currently calling your library from a .net standard 2.0 library.  I keep getting an system exception calling "new YoutubeConverter(client)".  It says "Value cannot be null.\nParameter name: path1".

It's really easy to create.  Just create a blank xamarin forms app using .net standard 2.0.  Add your library via nuget.  Then call your example code in the templated mainpage.xaml.cs

The code example I'm using is from your example...
var client = new YoutubeClient();
var converter = new YoutubeConverter(client);

**Comment by Tyrrrz** [comment]
Looks like it fails [here](https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/518285a8dec773cf37ba2fa5a3a28aa909001001/YoutubeExplode.Converter/YoutubeConverter.cs#L35) when it tries to get the path to FFmpeg. Can you try the other overload?

**Comment by scooby0344** [comment]
I will try this now and get back to you.  Thanks for the prompt reply.

**Comment by scooby0344** [comment]
That worked.  Thanks.

**Comment by Tyrrrz** [comment]
Still an issue though
