### ISSUE TITLE
Cannot find the file path when merging audio and video

### ISSUE THREAD

**Issue by Yaseen-Davids** [Tyrrrz/YoutubeExplode.Converter#6]
Hey, I've been using your code for one of my projects and it's been working great, however, when using YouTube Converter, I get the error "The system cannot find the specific file" when merging a video and audio stream.

This is a code snippet where I get the error:
`string filePath = Constants.DOWNLOAD_LOCATION + title;
await converter.DownloadAndProcessMediaStreamsAsync(mediaStreamInfos, filePath, "mp4", progress);`

The DOWNLOAD_LOCATION is "@"C:\Users\Name\Desktop\New folder\".

No matter what I change the "filePath" to, I get the same error. Perhaps I'm doing something wrong as I'm still a beginner with C#.

Could you please assist?

Thanks bro!

**Comment by Tyrrrz** [comment]
Hi @Yaseen-Davids 
This library requires ffmpeg binaries which are expected by default to be in the same directory as your executable. You can also configure it in the consutrctor.

**Comment by Yaseen-Davids** [comment]
Thanks for this.
Can you guide me to set that up?

Thanks

**Comment by Tyrrrz** [comment]
You can take a look at how tests are set up, most specifically this script: https://github.com/Tyrrrz/YoutubeExplode.Converter/blob/master/YoutubeExplode.Converter.Tests/DownloadFfmpeg.ps1

**Comment by Yaseen-Davids** [comment]
You're a genius. Thanks bro!

**Comment by Tyrrrz** [comment]
You're welcome :)
