### ISSUE TITLE
GetVideoMediaStreamInfosAsync always returns 0 Audio and Video stream infos

### ISSUE THREAD

**Issue by dauthleikr** [Tyrrrz/YoutubeExplode.Converter#7]
I pass the video ID given to me by `ParseVideoId` to it, but it always returns 0 infos:
![https://i.imgur.com/KTx2FrN.png](https://i.imgur.com/KTx2FrN.png)

I use Version 1.4.1 from nuget

**Comment by dauthleikr** [comment]
Just found https://github.com/Tyrrrz/YoutubeExplode/issues/229 it's caused by YT

**Comment by Tyrrrz** [comment]
Yes, you can update YT to latest beta version. It will be part of stable soon.

**Comment by Tyrrrz** [comment]
Should be fixed now
