### ISSUE TITLE
Is FFMPEG rendering the combined audio and video at 60fps?

### ISSUE THREAD

**Issue by Montegro** [Tyrrrz/YoutubeExplode.Converter#8]
Is there a way to prevent that and have it render them together at 24fps?

I might be wrong, but in trying out the converter and combining the streams I wound up with file sizes that are massive in comparison to the MUXED streams of YouTube. I know there's a discrepancy between 720p and 1080p obviously, but the muxed 720p resulted in a fifteen minute video coming out at 56MB, and the Converter's 1080p combined stream gave me a 707MB file. I expected (estimating from the video stream size and the audio stream size) that it should be around 180MB though, and I've been kinda knocking my head against a wall for a while here, but realized the potential explanation might be if FFMPEG is rendering a 60FPS file.

So, am I right? and if I am, is there a way we could boil down FFMPEG's rendered fps to 24 since that's what YouTube plays out any way?

**Comment by Tyrrrz** [comment]
Hi,
Besides higher maximum framerate and video quality, adaptive streams generally also have higher bitrate.
While it's not possible to tell YoutubeExplode.Converter to mux at specifically 24fps, you can instead use lower framerate streams as input, as described [here](https://github.com/Tyrrrz/YoutubeExplode.Converter#download-and-mux-specific-streams).

```c#
var client = new YoutubeClient();
var converter = new YoutubeConverter(client);

var mediaStreamInfoSet = await client.GetVideoMediaStreamInfosAsync("-qmBhoeQgv8");

var audioStreamInfo = mediaStreamInfoSet.Audio.WithHighestBitrate();

// This will sort the video streams from highest quality to lowest and then for each quality it will sort from lowest framerate to highest, and then pick the first one
var videoStreamInfo = mediaStreamInfoSet.Video.OrderByDescending(s => s.VideoQuality).ThenBy(s => s.Framerate).FirstOrDefault();

var mediaStreamInfos = new MediaStreamInfo[] { audioStreamInfo, videoStreamInfo };
await converter.DownloadAndProcessMediaStreamsAsync(mediaStreamInfos, "output-video.mp4", "mp4");
```

**Comment by Montegro** [comment]
That certainly worked to fetch the lower framerate video streams, but the file size still wound up being 707MB, so I think that lends more credence to my original assumption that ffmpeg is rendering these together at a higher framerate despite the video files being lower. It's a shame you can't have it mux at a lower framerate though since it seems to at least be doing 60FPS by default, though I can't check the exact fps until my video editing program gets reinstalled. Only issue I can really come up with is the file size, cause if each 15 minute video is almost 1GB, man am I gonna need every terabyte of my NAS! lol

**Comment by Tyrrrz** [comment]
Can you give me the video link so I can check?

**Comment by Montegro** [comment]
Weird, I suppose my question is wrong now, I got it into my video editing software, the framerate is infact 24fps. Still trying to figure out where all the extra data is from. You mentioned earlier that the highest bitrate is also way higher than YouTube's muxed streams, maybe I'm wrong but since it's audio I don't see that being the explanation for the over 500MB difference from my previous estimate of the filesize... Hmm

**Comment by Montegro** [comment]
> 
> 
> Can you give me the video link so I can check?

https://www.youtube.com/watch?v=Q-25c8Rsobw&list=PLaDrN74SfdT7Ueqtwn_bXo1MuSWT0ji2w&index=1

**Comment by Montegro** [comment]
Just finished trying to render the video down in VEGAS using 1080p settings on it to have framerates at 24fps and audio optimized for internet... it doubled the file size to 1.33GB. At this point I knew the framerates wouldnt be the issue, but it's just so odd to me that a video file of about 170mb and an audio file of about 16mb results in a mixed file of 707mb...

**Comment by Tyrrrz** [comment]
That is indeed odd but I don't have an answer to that question :)

**Comment by Montegro** [comment]
Alright, well thank you anyway for your help! The converter is very nice!

**Comment by Tyrrrz** [comment]
Thank you!

**Comment by Montegro** [comment]
I dug around in the Converter's source files to see the options used for ffmpeg, and then compared that all to ffmpeg's documentation, and I think I've solved the issue I was having. It appears as though using the option -preset ultrafast is the file size culprit, I just finished running ffmpeg to combine an audio and video stream using -preset medium, and the file size difference went from 707mb down to 242mb.

I plan on toying around with my copy of YouTubeExplode.Converter tomorrow morning (it's currently 4AM here as of writing) to see if I can't modify the _ffmpegCLI to allow for a list of options from the presets available in the ffmpeg documentation (ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, and veryslow) so that I could link a combobox to that same list and let my users choose the speed at which ffmpeg mux's the streams together.

Unless you've got a quick way to implement that?
Either way, I wanted to share my findings with you so you've got the information I've got on hand.

**Comment by Montegro** [comment]
I've prepped my own build that implements the rendering speed changes fairly well. If you're interested I can share it, though I'm not sure how @Tyrrrz

**Comment by Montegro** [comment]
Think I figured it out and proposed a branch. Let me know if I did that correctly, or your thoughts on the proposal.

**Comment by Tyrrrz** [comment]
Ah yeah, that makes sense. The preset was set to ultrafast because otherwise muxing takes an obnoxiously long time to complete.
Another thing to note, I really want to avoid exposing ffmpeg parameters directly in the API because this is meant as a full abstraction around it.
What is the output format of your video? Is it possible to do mp4+mp4 or webm+webm muxing?

**Comment by Montegro** [comment]
MP4, and yes it seems, only reason I can answer that off the top of my head is because that was my test run last night where I manually ran ffmpeg on a MP4 video and WebM audio file, and then later did MP4 and MP4. Why do you ask?

**Comment by Tyrrrz** [comment]
UYltrafast preset is only used when it's transcoding, i.e. the output encoding doesn't match input encoding (on at least one of the streams).
In other words:
- Mp4+Mp4 -> Mp4 = No transcoding
- WebM+WebM -> WebM = No transcoding
- Mp4+WebM -> Mp4 = Transcoding
- Mp4+Mp4 -> WebM = Transcoding

**Comment by Tyrrrz** [comment]
So if you supply mp4 streams and tell it to make a mp4 output stream then it should not transcode and not use ultrafast preset, but instead whatever is default, with probably smaller file size...

**Comment by Montegro** [comment]
I see, I haven't touched it too much since I tested it earlier, but from the sound of it I've got a couple more modifications to make then if I want to have it use the speed setting for pretty much everything then?

Is transcoding what ends up making the process take so long to render the video? I suppose what I mean by asking that is, if the transcoding doesn't need to happen then does the process not take long? For example if it was an MP4 and WEBM file being joined at medium preset speed, then that takes let's say 10 minutes for a 15 minute video. Does it take roughly that same amount of time when it's MP4 to MP4?

**Comment by Montegro** [comment]
Also it seems like if it were mp4+mp4 to webm then it wouldn't transcode either
![image](https://user-images.githubusercontent.com/1057035/57727721-359e1000-7660-11e9-8ea2-4247eeb903af.png)
just something I'm noticing...

So if it's performing the default preset, which is Medium according to ffmpeg's documentation, I don't imagine there would be any harm in overriding your check for if transcoding is necessary before changing the preset, and simply just set it to change the preset accordingly, right? Or am I overlooking something? I might be a little sleep deprived today.

**Comment by Tyrrrz** [comment]
>Is transcoding what ends up making the process take so long to render the video?
Yes. Muxing without transcoding is 100x faster.

> I don't imagine there would be any harm in overriding your check for if transcoding is necessary before changing the preset, and simply just set it to change the preset accordingly, right?
That's what it's doing now. :)

I suggest you try to use 2 mp4 streams on currently releasedversion and compare the results in regards to file size.

**Comment by Montegro** [comment]
Thank you for pointing me in that direction, you're absolutely right, if they don't need to be transcoded it's much faster to mux them and the filesize is genuinely fine. I'm gonna keep my branch on it's own though since that added control over transcoding speed is nice to have when it's necessary, you know?

**Comment by Tyrrrz** [comment]
Sure :)
