### ISSUE TITLE
Is there any way to load Closed Captions into the muxing?

### ISSUE THREAD

**Issue by Montegro** [Tyrrrz/YoutubeExplode.Converter#9]
Just out of curiosity, is there a way to add Closed Captions into the muxing process?

**Comment by Tyrrrz** [comment]
You generally don't need to as most players will pick up .srt files automatically if they have the same name as the video file. I know FFMPEG can burn subtitles into the video stream but not sure if you can inject them within the container. If you can, I think only mkv supports it.

**Comment by Montegro** [comment]
Alright, thank you
